// inserirIngressos.js
import { initializeApp } from "firebase/app";
import { getFirestore, collection, addDoc, doc, setDoc, getDoc, getDocs, query, where, writeBatch } from "firebase/firestore";

// 🔐 Substitua pelos dados reais do seu projeto Firebase
const firebaseConfig = {
  apiKey: "AIzaSyDscqWqHk_Atx7lHsAwvSQUKkmThXOEB6s",
  authDomain: "cine-senai.firebaseapp.com",
  projectId: "cine-senai",
  storageBucket: "cine-senai.firebasestorage.app",
  messagingSenderId: "507213086330",
  appId: "1:507213086330:web:00b2d42ce40bb519e545c3"
};

// Inicializa Firebase
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// 🔢 Lista embutida de compra de ingresso
const usuarios = [
  {
    "dataCompra": "2025-06-15T14:30:15-03:00",
    "dataSessao": "2025-06-15",
    "desconto": 50,
    "filme": "Olhos D'Água",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 12.5,
    "precoUnitario": 12.5,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "angelina.jolie@example.com",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr001",
    "usuarioNome": "Angelina Jolie",
    "valorEconomizado": 12.5
  },
  {
    "dataCompra": "2025-06-16T19:45:30-03:00",
    "dataSessao": "2025-06-16",
    "desconto": 0,
    "filme": "Jurassic World: Recomeço",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "leonardo.dicaprio@example.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": true,
    "usuarioId": "usr002",
    "usuarioNome": "Leonardo DiCaprio",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-17T10:15:45-03:00",
    "dataSessao": "2025-06-17",
    "desconto": 0,
    "filme": "Quarteto Fantástico",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "brad.pitt@example.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr003",
    "usuarioNome": "Brad Pitt",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-18T16:20:12-03:00",
    "dataSessao": "2025-06-18",
    "desconto": 60,
    "filme": "Eu sei o que fizeram no verão passado",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 10.0,
    "precoUnitario": 10.0,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "lady.gaga@example.com",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr004",
    "usuarioNome": "Lady Gaga",
    "valorEconomizado": 15.0
  },
  {
    "dataCompra": "2025-06-19T13:55:33-03:00",
    "dataSessao": "2025-06-19",
    "desconto": 50,
    "filme": "Superman: Deuses e Monstros",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 12.5,
    "precoUnitario": 12.5,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "zendaya@example.com",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr005",
    "usuarioNome": "Zendaya",
    "valorEconomizado": 12.5
  },
  {
    "dataCompra": "2025-06-20T20:10:22-03:00",
    "dataSessao": "2025-06-20",
    "desconto": 50,
    "filme": "Elio",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 12.5,
    "precoUnitario": 12.5,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "anitta@gmail.com",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr006",
    "usuarioNome": "Anitta",
    "valorEconomizado": 12.5
  },
  {
    "dataCompra": "2025-06-21T11:30:45-03:00",
    "dataSessao": "2025-06-21",
    "desconto": 0,
    "filme": "Olhos D'Água",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "caetano.veloso@terra.com.br",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr007",
    "usuarioNome": "Caetano Veloso",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-22T17:45:18-03:00",
    "dataSessao": "2025-06-22",
    "desconto": 30,
    "filme": "Jurassic World: Recomeço",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 17.5,
    "precoUnitario": 17.5,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "adele@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr008",
    "usuarioNome": "Adele",
    "valorEconomizado": 7.5
  },
  {
    "dataCompra": "2025-06-23T09:15:27-03:00",
    "dataSessao": "2025-06-23",
    "desconto": 0,
    "filme": "Quarteto Fantástico",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "bob.dylan@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr009",
    "usuarioNome": "Bob Dylan",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-24T15:22:41-03:00",
    "dataSessao": "2025-06-24",
    "desconto": 30,
    "filme": "Eu sei o que fizeram no verão passado",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 17.5,
    "precoUnitario": 17.5,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "beyonce@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr010",
    "usuarioNome": "Beyoncé",
    "valorEconomizado": 7.5
  },
  {
    "dataCompra": "2025-06-25T12:08:36-03:00",
    "dataSessao": "2025-06-25",
    "desconto": 0,
    "filme": "Superman: Deuses e Monstros",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "chico.buarque@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr011",
    "usuarioNome": "Chico Buarque",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-26T18:33:52-03:00",
    "dataSessao": "2025-06-26",
    "desconto": 60,
    "filme": "Elio",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 10.0,
    "precoUnitario": 10.0,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "dua.lipa@gmail.com",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr012",
    "usuarioNome": "Dua Lipa",
    "valorEconomizado": 15.0
  },
  {
    "dataCompra": "2025-06-27T14:17:29-03:00",
    "dataSessao": "2025-06-27",
    "desconto": 0,
    "filme": "Olhos D'Água",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "elis.regina@terra.com.br",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr013",
    "usuarioNome": "Elis Regina",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-28T21:45:15-03:00",
    "dataSessao": "2025-06-28",
    "desconto": 30,
    "filme": "Jurassic World: Recomeço",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 17.5,
    "precoUnitario": 17.5,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "frank.sinatra@uol.com.br",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr014",
    "usuarioNome": "Frank Sinatra",
    "valorEconomizado": 7.5
  },
  {
    "dataCompra": "2025-06-29T10:50:43-03:00",
    "dataSessao": "2025-06-29",
    "desconto": 0,
    "filme": "Quarteto Fantástico",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "gal.costa@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr015",
    "usuarioNome": "Gal Costa",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-30T16:25:38-03:00",
    "dataSessao": "2025-06-30",
    "desconto": 0,
    "filme": "Eu sei o que fizeram no verão passado",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "iggy.pop@globo.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr016",
    "usuarioNome": "Iggy Pop",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-07-01T13:12:21-03:00",
    "dataSessao": "2025-07-01",
    "desconto": 30,
    "filme": "Superman: Deuses e Monstros",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 17.5,
    "precoUnitario": 17.5,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "janis.joplin@hotmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr017",
    "usuarioNome": "Janis Joplin",
    "valorEconomizado": 7.5
  },
  {
    "dataCompra": "2025-07-02T19:38:54-03:00",
    "dataSessao": "2025-07-02",
    "desconto": 0,
    "filme": "Elio",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "joao.gilberto@ig.com.br",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr018",
    "usuarioNome": "João Gilberto",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-07-03T11:47:16-03:00",
    "dataSessao": "2025-07-03",
    "desconto": 50,
    "filme": "Olhos D'Água",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 12.5,
    "precoUnitario": 12.5,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "katy.perry@yahoo.com",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr019",
    "usuarioNome": "Katy Perry",
    "valorEconomizado": 12.5
  },
  {
    "dataCompra": "2025-07-04T17:23:35-03:00",
    "dataSessao": "2025-07-04",
    "desconto": 60,
    "filme": "Jurassic World: Recomeço",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 10.0,
    "precoUnitario": 10.0,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "lorde@bol.com.br",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr020",
    "usuarioNome": "Lorde",
    "valorEconomizado": 15.0
  },
  {
    "dataCompra": "2025-07-05T08:59:42-03:00",
    "dataSessao": "2025-07-05",
    "desconto": 0,
    "filme": "Quarteto Fantástico",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "madonna@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr021",
    "usuarioNome": "Madonna",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-07-06T15:14:28-03:00",
    "dataSessao": "2025-07-06",
    "desconto": 60,
    "filme": "Eu sei o que fizeram no verão passado",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 10.0,
    "precoUnitario": 10.0,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "marilia.mendonca@uol.com.br",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr022",
    "usuarioNome": "Marília Mendonça",
    "valorEconomizado": 15.0
  },
  {
    "dataCompra": "2025-07-07T12:41:37-03:00",
    "dataSessao": "2025-07-07",
    "desconto": 0,
    "filme": "Superman: Deuses e Monstros",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "neymar.jr@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr023",
    "usuarioNome": "Neymar Jr.",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-07-08T18:26:49-03:00",
    "dataSessao": "2025-07-08",
    "desconto": 60,
    "filme": "Elio",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 10.0,
    "precoUnitario": 10.0,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "olivia.rodrigo@uol.com.br",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr024",
    "usuarioNome": "Olivia Rodrigo",
    "valorEconomizado": 15.0
  },
  {
    "dataCompra": "2025-07-09T09:53:14-03:00",
    "dataSessao": "2025-07-09",
    "desconto": 0,
    "filme": "Olhos D'Água",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "paulo.gustavo@yahoo.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr025",
    "usuarioNome": "Paulo Gustavo",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-07-10T16:18:26-03:00",
    "dataSessao": "2025-07-10",
    "desconto": 0,
    "filme": "Jurassic World: Recomeço",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "queen.latifah@globo.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr026",
    "usuarioNome": "Queen Latifah",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-07-11T13:35:51-03:00",
    "dataSessao": "2025-07-11",
    "desconto": 30,
    "filme": "Quarteto Fantástico",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 17.5,
    "precoUnitario": 17.5,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "roberto.carlos@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr027",
    "usuarioNome": "Roberto Carlos",
    "valorEconomizado": 7.5
  },
  {
    "dataCompra": "2025-07-12T20:07:33-03:00",
    "dataSessao": "2025-07-12",
    "desconto": 60,
    "filme": "Eu sei o que fizeram no verão passado",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 10.0,
    "precoUnitario": 10.0,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "sia@terra.com.br",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr028",
    "usuarioNome": "Sia",
    "valorEconomizado": 15.0
  },
  {
    "dataCompra": "2025-07-13T11:42:18-03:00",
    "dataSessao": "2025-07-13",
    "desconto": 0,
    "filme": "Superman: Deuses e Monstros",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "taylor.swift@hotmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr029",
    "usuarioNome": "Taylor Swift",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-07-14T17:55:44-03:00",
    "dataSessao": "2025-07-14",
    "desconto": 30,
    "filme": "Elio",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 17.5,
    "precoUnitario": 17.5,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "vince.vaughn@bol.com.br",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr030",
    "usuarioNome": "Vince Vaughn",
    "valorEconomizado": 7.5
  },
  {
    "dataCompra": "2025-07-15T14:29:17-03:00",
    "dataSessao": "2025-07-15",
    "desconto": 0,
    "filme": "Olhos D'Água",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "whitney.houston@ig.com.br",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr031",
    "usuarioNome": "Whitney Houston",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-16T21:13:52-03:00",
    "dataSessao": "2025-06-16",
    "desconto": 0,
    "filme": "Jurassic World: Recomeço",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "xuxa.meneghel@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr032",
    "usuarioNome": "Xuxa Meneghel",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-17T08:48:25-03:00",
    "dataSessao": "2025-06-17",
    "desconto": 60,
    "filme": "Quarteto Fantástico",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 10.0,
    "precoUnitario": 10.0,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "yara.shahidi@uol.com.br",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr033",
    "usuarioNome": "Yara Shahidi",
    "valorEconomizado": 15.0
  },
  {
    "dataCompra": "2025-06-18T15:37:39-03:00",
    "dataSessao": "2025-06-18",
    "desconto": 0,
    "filme": "Eu sei o que fizeram no verão passado",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "zeca.pagodinho@terra.com.br",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr034",
    "usuarioNome": "Zeca Pagodinho",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-19T12:21:46-03:00",
    "dataSessao": "2025-06-19",
    "desconto": 50,
    "filme": "Superman: Deuses e Monstros",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 12.5,
    "precoUnitario": 12.5,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "angelina.jolie@example.com",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr035",
    "usuarioNome": "Angelina Jolie",
    "valorEconomizado": 12.5
  },
  {
    "dataCompra": "2025-06-20T18:56:13-03:00",
    "dataSessao": "2025-06-20",
    "desconto": 0,
    "filme": "Elio",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "leonardo.dicaprio@example.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": true,
    "usuarioId": "usr036",
    "usuarioNome": "Leonardo DiCaprio",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-21T09:34:57-03:00",
    "dataSessao": "2025-06-21",
    "desconto": 0,
    "filme": "Olhos D'Água",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "brad.pitt@example.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr037",
    "usuarioNome": "Brad Pitt",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-22T16:19:31-03:00",
    "dataSessao": "2025-06-22",
    "desconto": 60,
    "filme": "Jurassic World: Recomeço",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 10.0,
    "precoUnitario": 10.0,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "lady.gaga@example.com",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr038",
    "usuarioNome": "Lady Gaga",
    "valorEconomizado": 15.0
  },
  {
    "dataCompra": "2025-06-23T13:45:28-03:00",
    "dataSessao": "2025-06-23",
    "desconto": 50,
    "filme": "Quarteto Fantástico",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 12.5,
    "precoUnitario": 12.5,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "zendaya@example.com",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr039",
    "usuarioNome": "Zendaya",
    "valorEconomizado": 12.5
  },
  {
    "dataCompra": "2025-06-24T20:08:42-03:00",
    "dataSessao": "2025-06-24",
    "desconto": 50,
    "filme": "Eu sei o que fizeram no verão passado",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 12.5,
    "precoUnitario": 12.5,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "anitta@gmail.com",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr040",
    "usuarioNome": "Anitta",
    "valorEconomizado": 12.5
  },
  {
    "dataCompra": "2025-06-25T11:52:15-03:00",
    "dataSessao": "2025-06-25",
    "desconto": 0,
    "filme": "Superman: Deuses e Monstros",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "caetano.veloso@terra.com.br",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr041",
    "usuarioNome": "Caetano Veloso",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-26T18:27:59-03:00",
    "dataSessao": "2025-06-26",
    "desconto": 30,
    "filme": "Elio",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 17.5,
    "precoUnitario": 17.5,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "adele@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr042",
    "usuarioNome": "Adele",
    "valorEconomizado": 7.5
  },
  {
    "dataCompra": "2025-06-27T15:14:36-03:00",
    "dataSessao": "2025-06-27",
    "desconto": 0,
    "filme": "Olhos D'Água",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "bob.dylan@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr043",
    "usuarioNome": "Bob Dylan",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-28T12:39:48-03:00",
    "dataSessao": "2025-06-28",
    "desconto": 30,
    "filme": "Jurassic World: Recomeço",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 17.5,
    "precoUnitario": 17.5,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "beyonce@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr044",
    "usuarioNome": "Beyoncé",
    "valorEconomizado": 7.5
  },
  {
    "dataCompra": "2025-06-29T19:56:21-03:00",
    "dataSessao": "2025-06-29",
    "desconto": 0,
    "filme": "Quarteto Fantástico",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "chico.buarque@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr045",
    "usuarioNome": "Chico Buarque",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-30T10:23:54-03:00",
    "dataSessao": "2025-06-30",
    "desconto": 60,
    "filme": "Eu sei o que fizeram no verão passado",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 10.0,
    "precoUnitario": 10.0,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "dua.lipa@gmail.com",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr046",
    "usuarioNome": "Dua Lipa",
    "valorEconomizado": 15.0
  },
  {
    "dataCompra": "2025-07-01T17:41:37-03:00",
    "dataSessao": "2025-07-01",
    "desconto": 0,
    "filme": "Superman: Deuses e Monstros",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "elis.regina@terra.com.br",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr047",
    "usuarioNome": "Elis Regina",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-07-02T14:15:29-03:00",
    "dataSessao": "2025-07-02",
    "desconto": 30,
    "filme": "Elio",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 17.5,
    "precoUnitario": 17.5,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "frank.sinatra@uol.com.br",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr048",
    "usuarioNome": "Frank Sinatra",
    "valorEconomizado": 7.5
  },
  {
    "dataCompra": "2025-07-03T21:58:16-03:00",
    "dataSessao": "2025-07-03",
    "desconto": 0,
    "filme": "Olhos D'Água",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "gal.costa@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr049",
    "usuarioNome": "Gal Costa",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-07-04T08:34:43-03:00",
    "dataSessao": "2025-07-04",
    "desconto": 0,
    "filme": "Jurassic World: Recomeço",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "iggy.pop@globo.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr050",
    "usuarioNome": "Iggy Pop",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-07-05T15:47:52-03:00",
    "dataSessao": "2025-07-05",
    "desconto": 30,
    "filme": "Quarteto Fantástico",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 17.5,
    "precoUnitario": 17.5,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "janis.joplin@hotmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr051",
    "usuarioNome": "Janis Joplin",
    "valorEconomizado": 7.5
  },
  {
    "dataCompra": "2025-07-06T12:26:18-03:00",
    "dataSessao": "2025-07-06",
    "desconto": 0,
    "filme": "Eu sei o que fizeram no verão passado",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "joao.gilberto@ig.com.br",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr052",
    "usuarioNome": "João Gilberto",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-07-07T19:51:35-03:00",
    "dataSessao": "2025-07-07",
    "desconto": 50,
    "filme": "Superman: Deuses e Monstros",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 12.5,
    "precoUnitario": 12.5,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "katy.perry@yahoo.com",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr053",
    "usuarioNome": "Katy Perry",
    "valorEconomizado": 12.5
  },
  {
    "dataCompra": "2025-07-08T11:13:47-03:00",
    "dataSessao": "2025-07-08",
    "desconto": 60,
    "filme": "Elio",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 10.0,
    "precoUnitario": 10.0,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "lorde@bol.com.br",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr054",
    "usuarioNome": "Lorde",
    "valorEconomizado": 15.0
  },
  {
    "dataCompra": "2025-07-09T16:38:24-03:00",
    "dataSessao": "2025-07-09",
    "desconto": 0,
    "filme": "Olhos D'Água",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "madonna@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr055",
    "usuarioNome": "Madonna",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-07-10T13:24:51-03:00",
    "dataSessao": "2025-07-10",
    "desconto": 60,
    "filme": "Jurassic World: Recomeço",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 10.0,
    "precoUnitario": 10.0,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "marilia.mendonca@uol.com.br",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr056",
    "usuarioNome": "Marília Mendonça",
    "valorEconomizado": 15.0
  },
  {
    "dataCompra": "2025-07-11T20:49:38-03:00",
    "dataSessao": "2025-07-11",
    "desconto": 0,
    "filme": "Quarteto Fantástico",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "neymar.jr@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr057",
    "usuarioNome": "Neymar Jr.",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-07-12T09:16:12-03:00",
    "dataSessao": "2025-07-12",
    "desconto": 60,
    "filme": "Eu sei o que fizeram no verão passado",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 10.0,
    "precoUnitario": 10.0,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "olivia.rodrigo@uol.com.br",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr058",
    "usuarioNome": "Olivia Rodrigo",
    "valorEconomizado": 15.0
  },
  {
    "dataCompra": "2025-07-13T14:57:26-03:00",
    "dataSessao": "2025-07-13",
    "desconto": 0,
    "filme": "Superman: Deuses e Monstros",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "paulo.gustavo@yahoo.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr059",
    "usuarioNome": "Paulo Gustavo",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-07-14T18:32:49-03:00",
    "dataSessao": "2025-07-14",
    "desconto": 0,
    "filme": "Elio",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "queen.latifah@globo.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr060",
    "usuarioNome": "Queen Latifah",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-07-15T12:45:33-03:00",
    "dataSessao": "2025-07-15",
    "desconto": 30,
    "filme": "Olhos D'Água",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 17.5,
    "precoUnitario": 17.5,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "roberto.carlos@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr061",
    "usuarioNome": "Roberto Carlos",
    "valorEconomizado": 7.5
  },
  {
    "dataCompra": "2025-06-16T07:28:17-03:00",
    "dataSessao": "2025-06-16",
    "desconto": 60,
    "filme": "Jurassic World: Recomeço",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 10.0,
    "precoUnitario": 10.0,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "sia@terra.com.br",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr062",
    "usuarioNome": "Sia",
    "valorEconomizado": 15.0
  },
  {
    "dataCompra": "2025-06-17T16:54:41-03:00",
    "dataSessao": "2025-06-17",
    "desconto": 0,
    "filme": "Quarteto Fantástico",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "taylor.swift@hotmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr063",
    "usuarioNome": "Taylor Swift",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-18T11:37:28-03:00",
    "dataSessao": "2025-06-18",
    "desconto": 30,
    "filme": "Eu sei o que fizeram no verão passado",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 17.5,
    "precoUnitario": 17.5,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "vince.vaughn@bol.com.br",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr064",
    "usuarioNome": "Vince Vaughn",
    "valorEconomizado": 7.5
  },
  {
    "dataCompra": "2025-06-19T18:21:55-03:00",
    "dataSessao": "2025-06-19",
    "desconto": 0,
    "filme": "Superman: Deuses e Monstros",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "whitney.houston@ig.com.br",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr065",
    "usuarioNome": "Whitney Houston",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-20T13:46:14-03:00",
    "dataSessao": "2025-06-20",
    "desconto": 0,
    "filme": "Elio",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "xuxa.meneghel@gmail.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr066",
    "usuarioNome": "Xuxa Meneghel",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-21T20:59:37-03:00",
    "dataSessao": "2025-06-21",
    "desconto": 60,
    "filme": "Olhos D'Água",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 10.0,
    "precoUnitario": 10.0,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "yara.shahidi@uol.com.br",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr067",
    "usuarioNome": "Yara Shahidi",
    "valorEconomizado": 15.0
  },
  {
    "dataCompra": "2025-06-22T10:15:23-03:00",
    "dataSessao": "2025-06-22",
    "desconto": 0,
    "filme": "Jurassic World: Recomeço",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "zeca.pagodinho@terra.com.br",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr068",
    "usuarioNome": "Zeca Pagodinho",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-23T17:42:56-03:00",
    "dataSessao": "2025-06-23",
    "desconto": 50,
    "filme": "Quarteto Fantástico",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 12.5,
    "precoUnitario": 12.5,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "angelina.jolie@example.com",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr069",
    "usuarioNome": "Angelina Jolie",
    "valorEconomizado": 12.5
  },
  {
    "dataCompra": "2025-06-24T14:28:19-03:00",
    "dataSessao": "2025-06-24",
    "desconto": 0,
    "filme": "Eu sei o que fizeram no verão passado",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "leonardo.dicaprio@example.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": true,
    "usuarioId": "usr070",
    "usuarioNome": "Leonardo DiCaprio",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-25T21:53:42-03:00",
    "dataSessao": "2025-06-25",
    "desconto": 0,
    "filme": "Superman: Deuses e Monstros",
    "formaPagamento": "3",
    "pago": true,
    "precoTotal": 25.0,
    "precoUnitario": 25.0,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "brad.pitt@example.com",
    "usuarioEstudante": false,
    "usuarioFuncionario": false,
    "usuarioId": "usr071",
    "usuarioNome": "Brad Pitt",
    "valorEconomizado": 0.0
  },
  {
    "dataCompra": "2025-06-26T08:17:35-03:00",
    "dataSessao": "2025-06-26",
    "desconto": 60,
    "filme": "Elio",
    "formaPagamento": "4",
    "pago": true,
    "precoTotal": 10.0,
    "precoUnitario": 10.0,
    "quantidade": 1,
    "usuarioDeficiente": true,
    "usuarioEmail": "lady.gaga@example.com",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr072",
    "usuarioNome": "Lady Gaga",
    "valorEconomizado": 15.0
  },
  {
    "dataCompra": "2025-06-27T15:41:28-03:00",
    "dataSessao": "2025-06-27",
    "desconto": 50,
    "filme": "Olhos D'Água",
    "formaPagamento": "1",
    "pago": true,
    "precoTotal": 12.5,
    "precoUnitario": 12.5,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "zendaya@example.com",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr073",
    "usuarioNome": "Zendaya",
    "valorEconomizado": 12.5
  },
  {
    "dataCompra": "2025-06-28T12:24:51-03:00",
    "dataSessao": "2025-06-28",
    "desconto": 50,
    "filme": "Jurassic World: Recomeço",
    "formaPagamento": "2",
    "pago": true,
    "precoTotal": 12.5,
    "precoUnitario": 12.5,
    "quantidade": 1,
    "usuarioDeficiente": false,
    "usuarioEmail": "anitta@gmail.com",
    "usuarioEstudante": true,
    "usuarioFuncionario": false,
    "usuarioId": "usr074",
    "usuarioNome": "Anitta",
    "valorEconomizado": 12.5
  },

];

async function inserirIngressos() {
  try {
    const batch = writeBatch(db);
    const ingressosRef = collection(db, "ingressos");

    usuarios.forEach((usuario) => {
      const novoDoc = doc(ingressosRef);
      batch.set(novoDoc, {
        ...usuario,
        timestamp: new Date()
      });
    });

    await batch.commit();
    console.log("Ingressos inseridos com sucesso.");
  } catch (erro) {
    console.error("Erro ao inserir ingressos:", erro);
  }
}

inserirIngressos();